# Generated by Django 3.1.7 on 2021-03-16 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('AN', 'Any level'), ('BE', 'Beginner'), ('IN', 'Intermediate'), ('AD', 'Advanced')], default='AN', max_length=2)),
                ('type', models.CharField(choices=[('PO', 'Podcast'), ('YT', 'YouTube / Video'), ('CO', 'Online course (eg: Coursera)'), ('AR', 'Article, Text or Blog'), ('BO', 'Book'), ('OT', 'Other')], default='OT', max_length=2)),
                ('url', models.URLField(max_length=300)),
                ('description', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('likes', models.ManyToManyField(blank=True, related_name='link_like', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='links', to='links.Tag')),
            ],
        ),
    ]
