# Generated by Django 3.1.7 on 2021-03-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='tagline',
            field=models.CharField(default='', max_length=100),
        ),
    ]
