# Generated by Django 3.1.7 on 2021-03-12 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='link_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
