# Generated by Django 3.1.7 on 2021-03-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='links',
            new_name='link',
        ),
    ]
