# Generated by Django 3.1.7 on 2021-03-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20210328_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
